
# html lang
language: zh-CN

# main menu navigation
menu:
  # Li Xuetao: /
  About: /about
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/temp.css

# scripts loaded in the end of the body
scripts:
- /js/temp.js

social_icons:
  enable: true
  # Icon Mappings.
  # KeyMapsToSocalItemKey: NameOfTheIconFromFontAwesome
  GitHub: github
  Twitter: twitter
  Weibo: weibo
  Instagram: instagram

description: Life is fantastic :)